@startuml sequence-diagram
Alice -> Bob: Do you love me?
Bob --> Alice: Yes, I do.

Alice <- Bob: Do you love me?
Bob <-- Alice: No, I don't.

participant participantTag as prtc #Red
' comment
actor actorTag as actr
boundary boundaryTag as bndry
control controlTag as ctrl
entity entityTag as entty
database databaseTag as db
collections "collections \n Tag" as cllct #99FF99
queue queueTag as q

prtc -> actr: prtc to actr
prtc -> bndry: prtc to bndry
prtc -> ctrl: prtc to ctrl
entty -> db: entty to db
cllct -> prtc: cllct to prtc

@enduml