@startuml state-diagram
hide empty description

State1: This is a State1.

state StateA {
    State2: This is a State2.
    State3:

    state entry1 <<entryPoint>>
    state exit1 <<exitPoint>>

    state forkState1 <<fork>>
    state joinState1 <<join>>

    [*] --> forkState1
    forkState1 --> State2 
    forkState1 --> State3 
    State2 --> joinState1
    State3 --> joinState1
    joinState1 -> [*]
}

state StateB {
    State4: This is a State4.
    State5:

    [*] --> State4
    State4 --> State5
    State5 -> [*]
}

[*] --> State1
State1 --> entry1
note on link: this is a state-transition note.
exit1 --> StateB
note on link: this is a state-transition note2.
StateB --> [*]
note on link: this is a state-transition note3.

note right of State1: hogehoge
note top of StateB: Fugafuga
note "This is a floating note" as note
@enduml